package cl.calculos.model.fact.common;
// Generated 08-03-2018 17:23:58 by Hibernate Tools 5.2.3.Final

/**
 * OpeTmp generated by hbm2java
 */
public class OpeTmp implements java.io.Serializable {

	private int opeTmpId;
	private String nombre;

	public OpeTmp() {
	}

	public OpeTmp(int opeTmpId) {
		this.opeTmpId = opeTmpId;
	}

	public OpeTmp(int opeTmpId, String nombre) {
		this.opeTmpId = opeTmpId;
		this.nombre = nombre;
	}

	public int getOpeTmpId() {
		return this.opeTmpId;
	}

	public void setOpeTmpId(int opeTmpId) {
		this.opeTmpId = opeTmpId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
