package cl.calculos.model.fact.common;
// Generated 08-03-2018 17:23:58 by Hibernate Tools 5.2.3.Final

/**
 * TecnoTmp generated by hbm2java
 */
public class TecnoTmp implements java.io.Serializable {

	private int tecnoTmpId;
	private String nombre;

	public TecnoTmp() {
	}

	public TecnoTmp(int tecnoTmpId) {
		this.tecnoTmpId = tecnoTmpId;
	}

	public TecnoTmp(int tecnoTmpId, String nombre) {
		this.tecnoTmpId = tecnoTmpId;
		this.nombre = nombre;
	}

	public int getTecnoTmpId() {
		return this.tecnoTmpId;
	}

	public void setTecnoTmpId(int tecnoTmpId) {
		this.tecnoTmpId = tecnoTmpId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
